# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93fca71a0eb663c8a570fdfc7eff3169bf96cb83dc600fa59ab623b9aa06eae4b603e24553302d7c3e8927ad5d868a947f7a3c440c6d691fff3d7166834e3b69

test:
  secret_key_base: 0698d788eca9deeafa9a8887563fa0a0f50dd4147a6a477329dbc05fc0e391dbbefbad63b7b50471546c462c37dcd6f259d2055c78dac9d86cb9b7ec8a432d12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
